playlists:
    - id: '37i9dQZEVXbMDoHDwVN2tF'
      name: 'Top 50 - Global'
    - id: '37i9dQZEVXbLRQDuF5jeBp'
      name: 'Top 50 - USA'
    - id: '37i9dQZEVXbKj23U1GF4IR'
      name: 'Top 50 - Canada'
    - id: '37i9dQZEVXbMXbN3EUUhlg'
      name: 'Top 50 - Brazil'
    - id: '37i9dQZEVXbMMy2roB9myp'
      name: 'Top 50 - Argentina'
    - id: '37i9dQZEVXbJiZcmkrIHGU'
      name: 'Top 50 - Germany'
    - id: '37i9dQZEVXbIPWwFssbupI'
      name: 'Top 50 - France'
    - id: '37i9dQZEVXbNFJfN1Vw8d9'
      name: 'Top 50 - Spain'
    - id: '37i9dQZEVXbKkidEfWYRuD'
      name: 'Top 50 - Ukraine'
    - id: '37i9dQZEVXbMH2jvi6jvjk'
      name: 'Top 50 - South Africa'
    - id: '37i9dQZEVXbLn7RQmT5Xv2'
      name: 'Top 50 - Egypt'
    - id: '37i9dQZEVXbM4UZuIrvHvA'
      name: 'Top 50 - UAE'
    - id: '37i9dQZEVXbLrQBcXqUtaC'
      name: 'Top 50 - Saudi Arabia'
    - id: '37i9dQZEVXbKXQ4mDTEBXq'
      name: 'Top 50 - Japan'
    - id: '37i9dQZEVXbNxXF4SkHj9F'
      name: 'Top 50 - South Korea'
    - id: '37i9dQZEVXbLZ52XmnySJg'
      name: 'Top 50 - India'
    - id: '37i9dQZEVXbLnolsZ8PSNw'
      name: 'Top 50 - United Kingdom'
    - id: '37i9dQZEVXbKY7jLzlJ11V'
      name: 'Top 50 - Nigeria'

#playlists_id:
#    - '37i9dQZEVXbMDoHDwVN2tF'
#    - '37i9dQZEVXbLRQDuF5jeBp'
#    - '37i9dQZEVXbKj23U1GF4IR'
#    - '37i9dQZEVXbMXbN3EUUhlg'
#    - '37i9dQZEVXbMMy2roB9myp'
#    - '37i9dQZEVXbJiZcmkrIHGU'
#    - '37i9dQZEVXbIPWwFssbupI'
#    - '37i9dQZEVXbNFJfN1Vw8d9'
#    - '37i9dQZEVXbKkidEfWYRuD'
#    - '37i9dQZEVXbMH2jvi6jvjk'
#    - '37i9dQZEVXbLn7RQmT5Xv2'
#    - '37i9dQZEVXbM4UZuIrvHvA'
#    - '37i9dQZEVXbLrQBcXqUtaC'
#    - '37i9dQZEVXbKXQ4mDTEBXq'
#    - '37i9dQZEVXbNxXF4SkHj9F'
#    - '37i9dQZEVXbLZ52XmnySJg'
#    - '37i9dQZEVXbLnolsZ8PSNw'
#    - '37i9dQZEVXbKY7jLzlJ11V'
